apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdb-pvc
  namespace: adi-wordpress-app 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-adi

