apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-adi
  namespace: adi-wordpress-app
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
